spring:
  application:
    name: eureka-server

server:
  port: 8080
eureka:
  instance:
    hostname: eureka-server
    appname: 注册中心
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000