spring:
  application:
    name: register-server
server:
  port: 8080

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${MY_POD_NAME}.register-server #设置eureka hostname
    prefer-ip-address: false #不使用ip注册，因为eureka相互注册的工程中，使用的服务名，例如register-server-0.register-server，如果使用ip注册，会导致eureka认为其他副本不可用，即eureka服务都会出现在unavailable-replicas中，而不是available-replicas中
  client:
    # //表示是否从Eureka Server获取注册的服务信息
    fetch-registry: false
    # 注册中心将自己作为客户端来尝试注册自己，注册中心集群环境下需开启此配置 # 单点的时候设置为 false 禁止注册自身
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://register-server-0.register-server:8080/eureka/,http://register-server-1.register-server:8080/eureka/,http://register-server-2.register-server:8080/eureka/